name: Build and Deploy

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print Version Name
      run: echo ${{ github.ref_name }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        tags: abdfaiyaz/ms:${{github.ref_name}}
        cache-from: type=gha,scope=ms
        cache-to: type=gha,mode=max,scope=ms

#release create korar time ee